apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: deployment-role
rules:
- apiGroups: ["apps",""]
  resources: ["deployments","pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-rolebind
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-robot # Name of the ServiceAccount
  namespace: default
roleRef:
  kind: ClusterRole # This must be Role or ClusterRole
  name: deployment-role # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziglu-deployment
  labels:
    app: ziglu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziglu
  template:
    metadata:
      labels:
        app: ziglu
    spec:
      containers:
      - name: ziglu
        image: docker.io/yellowzone/ziglu:latest
        ports:
        - containerPort: 5555
      serviceAccountName: deployment-robot  # Name of the ServiceAccount
