apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziglu-deployment
  labels:
    app: ziglu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ziglu
  template:
    metadata:
      labels:
        app: ziglu
    spec:
      containers:
      - name: ziglu
        image: docker.io/yellowzone/ziglu:latest
        ports:
        - containerPort: 5555
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-list
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["list"]
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
